### ISSUE TITLE
Titel für den Kontakt wird im Theme in der Sidebar nicht angezeigt

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Medfak#1]
https://www.tst.med.fau.de/beispiel-seite/

**Comment by xwolfde** [comment]
Nicht nachvollziehbar, weil die Seite nicht existiert.
Bitte auch bei Problemen mit Funktionen aus den Personen/Kontakten nicht beim Theme, sondern beim Personen-Plugin selbst eintragen
