### ISSUE TITLE
Merkwürdige Darstellung des "g" in Kursivschrift

### ISSUE THREAD

**Issue by UNiederweis** [RRZE-Webteam/FAU-Medfak#10]
Bitte screenshots prüfen.
![komische darstellung g 3](https://cloud.githubusercontent.com/assets/13850998/9329608/4619b646-45b3-11e5-9c22-a951f5b9e94f.jpg)
![komische darstellung g 2](https://cloud.githubusercontent.com/assets/13850998/9329610/461c96ae-45b3-11e5-9ec1-908723e40bf3.jpg)
![komische darstellung g](https://cloud.githubusercontent.com/assets/13850998/9329609/461b295e-45b3-11e5-8a31-6c12f5c768eb.jpg)

**Comment by xwolfde** [comment]
Bestätigt. Es handelt sich um ein Problem, welches aber nur unter Windows auftritt. Andere Systeme sind wohl nicht betroffen.
Da die verwendete Hausschrift der FAU, die hier zum Einsatz kommt, nicht von uns geändert werden kann, können wir da auch nichts tun.

Allerdings sollte man die Kursivschrifteigentlich garnicht verwenden. Wenn Zitate verwendet werden soll, ist das "Zitat"-Symbol bzw in HTML: "blockquote" das richtige. Wenn es darum geht, besondere Bereiche zu kennzeichnen, sollte man dazu entweder einen gesonderten Hinweis-Block nutzen (dazu werde ich mal ein Issue anlegen, um dies als Shortcode zu ergänzen) oder aber einen eigenen Absatz mit passender Überschrift.

Übrigens: Bei der FAU-Website ist die Verwendung von Kursivschrift den Redakteuren laut Herrn Busch auch untersagt worden.

**Comment by j-hofmann** [comment]
fyi: tritt mit einer aktuelleren Version von Roboto-Italic.ttf nicht mehr auf

**Comment by xwolfde** [comment]
Ah, danke für den Hinweis. Dann werde ich das mal für das nächste Update vorsehen.
Ich warte dann aber auch noch auf das Update von Awesome, da dort auch die neuen Google-Logos kommen werden

**Comment by xwolfde** [comment]
ist tatsächlich in der neuen Version behoben
