### ISSUE TITLE
Nochmal das Theme und die Farben

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#12]
Vorneweg: Ich bin begeistert, das ist - über alle Themes hinweg - meiner Ansicht nach jetzt deutlich schöner. Eine Kleinigkeit, die ich als störend empfinde, ist im Medfak-Theme die Schattenschrift, die den Hinweis aufs Portal gibt, und das darunter liegende Siegel. Das sieht bei der Phil, wo das Siegel dunkler ist als der Hintergrund sehr schön aus. Bei der Med, wo das Siegel helltürkis ist und von der hellblauen Schrift überlagert wird, ist das meiner Ansicht nach zu unruhig. Könnte man daran noch etwas drehen oder ist das zu aufwendig?
![bildschirmfoto 2015-08-20 um 10 40 45](https://cloud.githubusercontent.com/assets/11296947/9379299/8bdeef40-4728-11e5-8dc6-ceee2994f0fb.png)

**Comment by xwolfde** [comment]
Wird wie besprochen in dunklerer Form umgesetzt

**Comment by xwolfde** [comment]
im nächsten update in dunkler.
