### ISSUE TITLE
komische Darstellung der Seite

### ISSUE THREAD

**Issue by UNiederweis** [RRZE-Webteam/FAU-Medfak#13]
obwohl ich alles gleich formatiert habe 
ich kann den fehler nicht ausmerzen (fehlender/falscher Umbruch blaek zu bäk)
![2015-08-20 13_32_33-greenshot](https://cloud.githubusercontent.com/assets/13850998/9382366/79c84a28-4740-11e5-9ac3-660424af969b.jpg)

**Comment by AstridSemm** [comment]
Derzeit ist die Lösung zu diesem Problem entweder eine Liste (wobei sich das Problem mit den Grafiken eventuell weiterhin ergibt) oder eine Tabelle.
Auf lange Sicht werden wir für solche Zwecke die Galeriefunktion entsprechend anpassen, so dass Grafik und Bildunterschrift in der Galerie mit Links versehen werden können.

Noch eine kleine Anmerkung: Bitte nicht die Grafiken von anderen Seiten her verlinken; die meisten Webmaster mögen so etwas gar nicht, weil man damit den eigenen Traffic auf den Server derer verlagert, von denen man das Bild holt. In diesem Fall wird das nicht so wild sein, aber man sollte es sich generell zur Regel machen.

**Comment by xwolfde** [comment]
Für solche Verlinkungen kann das Template portalindex genutzt werden indem dann die Bildlink-Funktion genutzt wird. Alternativ Portalmenu mit extern. Links.
