### ISSUE TITLE
Default-Aufforderung Login-Seite

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Medfak#16]
Wenn man eine Seite passwortschützt, werden die User aufgefrodert, dieses dann einzugeben. Die Default-Afforderung (der Text) muss korrigiert (Ihr groß schreiben) und sollte geändert werden. 

Vorschlag: "Um die Seite besuchen zu können, geben Sie bitte Ihr Passwort ein."
![bildschirmfoto 2015-08-27 um 13 02 38](https://cloud.githubusercontent.com/assets/11868989/9519085/097d8b58-4cbc-11e5-95bf-47686a8ac6c6.png)

**Comment by xwolfde** [comment]
Kommt aus WordPress Language Paket. Da können wir nichts tun.
