### ISSUE TITLE
Thema Verlinken

### ISSUE THREAD

**Issue by UNiederweis** [RRZE-Webteam/FAU-Medfak#17]
kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by steffigebel** [comment]
Liebe Frau Niederweis,

da wir alle Profis sind und nur das beste für Sie und Ihre Website-Besucher wollen, können wir Ihren Wunsch leider nicht berücksichtigen ;-) So was macht man nicht. Die Gründe finden Sie u. a. hier http://www.media-affin.de/gruende-gegen-target-blank: 1) der User wird daruch bevormundet, 2) der Befehl würde den User-PC zuspamen, Zurück-Button der Zielseite und Mausgesten funktionieren dadurch nicht, 4) der Befehl ist ein Webdesign-Fehler und sollte gar nicht zum Einsatz kommen 5) Validität nicht immer gegeben.

Also, ich denke, Sie wollen das dann doch nicht ;-)

Grüße,
Steffi Gebel und das Webteam

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 27. August 2015 14:31
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Betreff: [FAU-Medfak] Thema Verlinken (#17)


kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by UNiederweis** [comment]
Naja, die Bevormundung war schon gewünscht, weil ich sonst händisch alle Links von allen Redakteuren einzeln kontrollieren muss dahingehend, ob das Häkchen gesetzt ist …

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:02
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Liebe Frau Niederweis,

da wir alle Profis sind und nur das beste für Sie und Ihre Website-Besucher wollen, können wir Ihren Wunsch leider nicht berücksichtigen ;-) So was macht man nicht. Die Gründe finden Sie u. a. hier http://www.media-affin.de/gruende-gegen-target-blank: 1) der User wird daruch bevormundet, 2) der Befehl würde den User-PC zuspamen, Zurück-Button der Zielseite und Mausgesten funktionieren dadurch nicht, 4) der Befehl ist ein Webdesign-Fehler und sollte gar nicht zum Einsatz kommen 5) Validität nicht immer gegeben.

Also, ich denke, Sie wollen das dann doch nicht ;-)

Grüße,
Steffi Gebel und das Webteam

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 27. August 2015 14:31
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>
Betreff: [FAU-Medfak] Thema Verlinken (#17)


kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by steffigebel** [comment]
Ich gebe die Empfehlung, die Häckchen nicht zu setzen. Aus genannten Gründen.


Von: UNiederweis <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 27. August 2015 15:03
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Naja, die Bevormundung war schon gewünscht, weil ich sonst händisch alle Links von allen Redakteuren einzeln kontrollieren muss dahingehend, ob das Häkchen gesetzt ist …

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de><mailto:ursula.niederweis@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:02
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Liebe Frau Niederweis,

da wir alle Profis sind und nur das beste für Sie und Ihre Website-Besucher wollen, können wir Ihren Wunsch leider nicht berücksichtigen ;-) So was macht man nicht. Die Gründe finden Sie u. a. hier http://www.media-affin.de/gruende-gegen-target-blank: 1) der User wird daruch bevormundet, 2) der Befehl würde den User-PC zuspamen, Zurück-Button der Zielseite und Mausgesten funktionieren dadurch nicht, 4) der Befehl ist ein Webdesign-Fehler und sollte gar nicht zum Einsatz kommen 5) Validität nicht immer gegeben.

Also, ich denke, Sie wollen das dann doch nicht ;-)

Grüße,
Steffi Gebel und das Webteam

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com><mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 27. August 2015 14:31
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com><mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>
Betreff: [FAU-Medfak] Thema Verlinken (#17)


kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by UNiederweis** [comment]
Ja, habe ich schon verstanden und akzeptiert, ich wollte nur meine Hintergründe nochmal darstellen ☺

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:21
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Ich gebe die Empfehlung, die Häckchen nicht zu setzen. Aus genannten Gründen.


Von: UNiederweis <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 27. August 2015 15:03
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>>
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Naja, die Bevormundung war schon gewünscht, weil ich sonst händisch alle Links von allen Redakteuren einzeln kontrollieren muss dahingehend, ob das Häkchen gesetzt ist …

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de><mailto:ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de%3cmailto:ursula.niederweis@fau.de%3e%3cmailto:ursula.niederweis@fau.de>>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:02
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Liebe Frau Niederweis,

da wir alle Profis sind und nur das beste für Sie und Ihre Website-Besucher wollen, können wir Ihren Wunsch leider nicht berücksichtigen ;-) So was macht man nicht. Die Gründe finden Sie u. a. hier http://www.media-affin.de/gruende-gegen-target-blank: 1) der User wird daruch bevormundet, 2) der Befehl würde den User-PC zuspamen, Zurück-Button der Zielseite und Mausgesten funktionieren dadurch nicht, 4) der Befehl ist ein Webdesign-Fehler und sollte gar nicht zum Einsatz kommen 5) Validität nicht immer gegeben.

Also, ich denke, Sie wollen das dann doch nicht ;-)

Grüße,
Steffi Gebel und das Webteam

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>><mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com%3cmailto:notifications@github.com>>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>><mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>>
Datum: Donnerstag, 27. August 2015 14:31
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>><mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>>
Betreff: [FAU-Medfak] Thema Verlinken (#17)


kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by steffigebel** [comment]
;-)

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Donnerstag, 27. August 2015 15:21
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Ja, habe ich schon verstanden und akzeptiert, ich wollte nur meine Hintergründe nochmal darstellen ☺

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de><mailto:ursula.niederweis@fau.de>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:21
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Ich gebe die Empfehlung, die Häckchen nicht zu setzen. Aus genannten Gründen.


Von: UNiederweis <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com><mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>
Datum: Donnerstag, 27. August 2015 15:03
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com><mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de><mailto:stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de%3cmailto:stefanie.gebel@fau.de>>>
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Naja, die Bevormundung war schon gewünscht, weil ich sonst händisch alle Links von allen Redakteuren einzeln kontrollieren muss dahingehend, ob das Häkchen gesetzt ist …

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de><mailto:ursula.niederweis@fau.de><mailto:ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de%3cmailto:ursula.niederweis@fau.de%3e%3cmailto:ursula.niederweis@fau.de>>

Von: Steffi [mailto:notifications@github.com]
Gesendet: Donnerstag, 27. August 2015 15:02
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Thema Verlinken (#17)

Liebe Frau Niederweis,

da wir alle Profis sind und nur das beste für Sie und Ihre Website-Besucher wollen, können wir Ihren Wunsch leider nicht berücksichtigen ;-) So was macht man nicht. Die Gründe finden Sie u. a. hier http://www.media-affin.de/gruende-gegen-target-blank: 1) der User wird daruch bevormundet, 2) der Befehl würde den User-PC zuspamen, Zurück-Button der Zielseite und Mausgesten funktionieren dadurch nicht, 4) der Befehl ist ein Webdesign-Fehler und sollte gar nicht zum Einsatz kommen 5) Validität nicht immer gegeben.

Also, ich denke, Sie wollen das dann doch nicht ;-)

Grüße,
Steffi Gebel und das Webteam

Von: UNiederweis <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com>><mailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com<mailto:notifications@github.com%3cmailto:notifications@github.com%3cmailto:notifications@github.com>>>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com><mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com>><mailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com<mailto:reply@reply.github.com%3cmailto:reply@reply.github.com%3cmailto:reply@reply.github.com>>>>
Datum: Donnerstag, 27. August 2015 14:31
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com><mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>><mailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com%3cmailto:FAU-Medfak@noreply.github.com>>>>
Betreff: [FAU-Medfak] Thema Verlinken (#17)


kann man systemseitig die Einstellungen bitte so ändern, dass automatisch der Link in einem neuen Fenster geöffnet wird (sprich: der Haken gesetzt ist), und nur, wenn das nicht gewünscht ist, wir ihn aktiv entfernen müssen?
Das würde uns einiges an Arbeit ersparen :-)

**Comment by xwolfde** [comment]
Wir haben übrigens genau das Gegenteil vor: Serverseitig festlegen, daß es das Häckchen nicht mehr gibt und jegliche Verwendung von target in Links zu verhindern.
Wie Frau gebel richtig andeutete: Die Verwendung von Targets, die ein neues Fenster öffnen, stellt für viele Endnutzer eine Barriere dar, welche verhindert, daß die Seite weiter benutzt werden kann...
