### ISSUE TITLE
Erweiterung Assistent

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#18]
Den Assistenten so erweitern, dass nicht nur die Unterseiten eines Parent angezeigt werden, sondern man auch einzelne Seiten für die Anzeige auswählen kann.

**Comment by xwolfde** [comment]
Da müssen wir wirklich ran. So ist der Assistent wirklich nicht so alltagstauglich. Wir müssen aber dennoch abwärtskompatibel bleiben, sonst werden wir von der Webredaktion gefressen :)

Meine Ideen:

Wir fügen folgende neue Attribute hinzu:

pages="childs"
   Default - wie jetzt. Es wird eine (1) Id in "id="" verwendet. Alle Seiten, die Kinder dieser Seite sind werden dargestellt.
 
pages="id"
   Es werden die Seite der Einträge aus id="" gezeigt. D.h. dann können auch mehrere Ids eingegeben  
   werden. Childs werden dann nicht gesucht.



Ausserdem finde ich es blöd, daß immer der gesamte Seiteninhalt angezeigt wird. IMHO wäre die Funktion hilfreicher nutzbar, wenn man ein Auszug der Seiten anzeigen lassen könnte.
ggf. ein textauszug und daneben auch via Option das beitragsbild.

Dazu wären ggf. folgende Optionen im Shortcode denkbar:

display="all"
   Default - zeigt wie jetzt alles.

display="excerpt"
   Zeigt von den Seiten einen Auszug. Wenn es keinen gibt aus einem extra Feld, dann ermittle einen Anhand der ersten n zeichen.

display="excerptthumb"
   Zeigt von den Seiten einen Auszug. Wenn es keinen gibt aus einem extra Feld, dann ermittle einen Anhand der ersten n zeichen. Zeige das ganze in einer Spalte rechts. Links kommt eine Spalte mit dem Seitenbild.

**Comment by xwolfde** [comment]
Zurückgestellt, da kein Bedarf
