### ISSUE TITLE
Seitensuche nach ID ermöglichen

### ISSUE THREAD

**Issue by UNiederweis** [RRZE-Webteam/FAU-Medfak#19]
Das würde manche Suche erheblich verkürzen :-)

**Comment by xwolfde** [comment]
Nein, das macht keinen Sinn:
Wenn man die ID kennt, weiß man als Admin auch welche Seite es ist. Denn woher sollte man die ID sonst kennen.

**Comment by UNiederweis** [comment]
also, ich habe die Seite nicht gebastelt und habe nun trotz diverser Suchbefehle aufwändig suchen  müssen, um Seiten, deren ID ich aus dem Assistenten kannte, zu finden ….

Mit freundlichen Grüßen

Ursula Niederweis, M.A.
Dekanat der Medizinischen Fakultät
Friedrich Alexander Universität Erlangen-Nürnberg
Krankenhausstr. 12, Bauteil F, Raum 02.112
91054 Erlangen
Tel.: 09131-85-23708
Fax: 09131-85-23704
E-Mail: ursula.niederweis@fau.de<mailto:ursula.niederweis@fau.de>

Von: Wolfgang Wiese [mailto:notifications@github.com]
Gesendet: Montag, 7. September 2015 15:23
An: RRZE-Webteam/FAU-Medfak
Cc: Niederweis, Ursula
Betreff: Re: [FAU-Medfak] Seitensuche nach ID ermöglichen (#19)


Nein, das macht keinen Sinn:
Wenn man die ID kennt, weiß man als Admin auch welche Seite es ist. Denn woher sollte man die ID sonst kennen.

**Comment by xwolfde** [comment]
Der Assistent wird aber derzeit nicht mit Ids von Seiten befüllt. 
Und selbst wenn er das mal wird: Dann wissen Sie doch welche Ids zu welcher Seite gehören, weil Sie die Seiten vorher ausgewählt haben um danach von diesen die Ids anzugeben.

Das man bei bekannter ID nach einer Seite suchen muss ist doch auch Unsinn. Die Seite ist doch dann eindeutig bekannt. Man ruft dann einfach die Seite mit der ID auf... 
z.B. DOMAINNAME?p=1130695  wenn die Id 1130695 ist.

Eine solche zusätzliche Suche würde nur mehr Verwirrung stiften als das sie nutzt, daher: Nein.
