### ISSUE TITLE
Hilfe zu Bildlinks nicht wirklich hilfreich

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#2]
In der Hilfe zu den Bildlinks gibt es eine Übersicht über die shortcodes. Das ist zwar nett, hilft dem Benutzer aber nicht wirklich weiter (vor allem, wenn er herausfinden will, wie Bildlinks und wpSEO zusammenhängen). Screenshot:
![bildschirmfoto 2015-08-03 um 09 20 20 kopie](https://cloud.githubusercontent.com/assets/11296947/9032745/0b017d52-39c2-11e5-9345-313745231f60.png)

**Comment by xwolfde** [comment]
Ich glaub das kommt von dem RRZE Shortcode Plugin...
Wer mag? @endv02

**Comment by endv02** [comment]
OK, ich geh der Sache auf den Grund

**Comment by steffigebel** [comment]
Top!
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: endv02 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Montag, 3. August 2015 11:06
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Betreff: Re: [FAU-Medfak] Hilfe zu Bildlinks nicht wirklich hilfreich (#2)


OK, ich geh der Sache auf den Grund

**Comment by endv02** [comment]
So, ist im rrze-shortcodes-Plugin behoben

**Comment by steffigebel** [comment]
Was hat das nmit Shortcodes zu tun? Nur für mich, weil ich es einfach nicht weiss und mich wundere, weil cih es da nicht erwartet hätte!
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: endv02 <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Mittwoch, 5. August 2015 13:30
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Medfak] Hilfe zu Bildlinks nicht wirklich hilfreich (#2)


So, ist im rrze-shortcodes-Plugin behoben
