### ISSUE TITLE
Datum eingeben beim Top-Event

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#22]
Wenn man beim Top-Event ein Datum angeben möchte, bekommt man einen Kalender angezeigt, in dem man eigentlich nur das Datum anklicken müsste - wenn man es denn sähe. Das sieht mir reparaturbedürftig aus. 
Firefox
![bildschirmfoto 2015-09-22 um 12 04 38](https://cloud.githubusercontent.com/assets/11296947/10015729/68b98868-6122-11e5-988b-d54023dc50eb.png)
Chrome
![bildschirmfoto 2015-09-22 um 12 08 31](https://cloud.githubusercontent.com/assets/11296947/10015790/bceef27e-6122-11e5-8d03-d2682354a292.png)
Safari
![bildschirmfoto 2015-09-22 um 12 13 03](https://cloud.githubusercontent.com/assets/11296947/10015894/5a8cccc2-6123-11e5-9611-faf360c306ee.png)
Opera macht die mouseover-Geschichte gar nicht erst mit, stellt dafür auf Klick aber richtig dar
![bildschirmfoto 2015-09-22 um 12 11 14](https://cloud.githubusercontent.com/assets/11296947/10015847/0fd9a8e4-6123-11e5-92ec-1f7fc3cd65a4.png)
Einen Explorer habe ich gerade nicht zur Hand.

**Comment by xwolfde** [comment]
Ja, Browserbugs

**Comment by AstridSemm** [comment]
Wo wird das Datum, das man da eingibt, eigentlich im Frontend angezeigt? Beim Top-Event selbst sehe ich es nicht...

**Comment by xwolfde** [comment]
es auch behoben
