### ISSUE TITLE
Chrome hat Probleme mit dem Menü im Dashboard

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#23]
Ich habe mal ein paar screenshots gemacht; es scheint, als ob die mouseover-Events beim Überfahren der Menüpunkte nicht sauber dargestellt würden. Ob das ein bug im Menü ist oder einer im Browser kann ich nicht beurteilen, deshalb deklariere ich es mal als bug.
![bildschirmfoto 2015-09-22 um 12 19 00](https://cloud.githubusercontent.com/assets/11296947/10016063/8c227c04-6124-11e5-8760-bff846a1eff9.png)
![bildschirmfoto 2015-09-22 um 12 19 15](https://cloud.githubusercontent.com/assets/11296947/10016065/8dea8626-6124-11e5-82a4-94c862a73285.png)
![bildschirmfoto 2015-09-22 um 12 19 33](https://cloud.githubusercontent.com/assets/11296947/10016070/91d0f004-6124-11e5-86b0-49dc6603b266.png)
![bildschirmfoto 2015-09-22 um 12 17 54](https://cloud.githubusercontent.com/assets/11296947/10016071/936e9452-6124-11e5-8ca7-78059ad43706.png)
![bildschirmfoto 2015-09-22 um 12 19 47](https://cloud.githubusercontent.com/assets/11296947/10016072/950b1efc-6124-11e5-8bd0-3f1ad4ea4704.png)

**Comment by xwolfde** [comment]
Browserbug. Nicht unsere Sache.
