### ISSUE TITLE
Bonusfrage Top-Event: Wofür wird das Datum angegeben?

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#24]
Ich stehe ein wenig auf dem Schlauch: Man kann ja einem Top-Event ein Datum hinzufügen. Das wird beim einzelnen Top-Event aber nicht angegeben. Wofür ist das dann?

**Comment by xwolfde** [comment]
In der nächsten version wird das Datum von Topevents angezeigt
