### ISSUE TITLE
Überschriften Bühnenmenü

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#25]
Im Bühnenmenü sind die Überschriften neuerdings weiß hinterlegt. Wie kommt das denn?
![bildschirmfoto 2015-09-25 um 09 56 16](https://cloud.githubusercontent.com/assets/11296947/10095698/e9fe1812-636b-11e5-805c-ecbd54166982.png)
![bildschirmfoto 2015-09-25 um 09 56 53](https://cloud.githubusercontent.com/assets/11296947/10095700/ec372b82-636b-11e5-8d85-f304cd3f1f74.png)

**Comment by steffigebel** [comment]
Im Chrome nicht!
--
Steffi Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Astrid <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 25. September 2015 09:58
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Betreff: [FAU-Medfak] Überschriften Bühnenmenü (#25)


Im Bühnenmenü sind die Überschriften neuerdings weiß hinterlegt. Wie kommt das denn?
[bildschirmfoto 2015-09-25 um 09 56 16]<https://cloud.githubusercontent.com/assets/11296947/10095698/e9fe1812-636b-11e5-805c-ecbd54166982.png>
[bildschirmfoto 2015-09-25 um 09 56 53]<https://cloud.githubusercontent.com/assets/11296947/10095700/ec372b82-636b-11e5-8d85-f304cd3f1f74.png>

**Comment by xwolfde** [comment]
Behoben. Problem lag in den ELFI-Plugin, welches Styles überschrieb
