### ISSUE TITLE
Bildurheberangabe gibt "unknown" zurück

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#26]
Eigentlich sollte doch, wenn in den Bild-Metatags nichts steht, die Angabe aus der Bildbeschreibung genommen werden? Oder steht in den Metatags "unknown"? Das Problem ist hier in voller Schönheit zu bewundern: https://www.tst.med.fau.de/2015/09/29/einfuehrungsveranstaltung-fuer-studienanfaenger/

Screenshot für Eilige:
![bildschirmfoto 2015-09-30 um 15 40 22](https://cloud.githubusercontent.com/assets/11296947/10194593/ea35fec2-6789-11e5-9ae4-331df0acf4a7.png)

**Comment by xwolfde** [comment]
Alles richtig: Im EXIF des Bildes steht bei Author "unknown".
Genau um sowas nachzuchecken gibt es die Bild-Attachment-Seite die für angemeldete User alle Metadaten zeigt. 
Alternativ tut es sowas wie Photoshop auch :P
