### ISSUE TITLE
Externe Links kennzeichnen

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#27]
Nachdem 'class="extern"' keinen Effekt hat, brauchen wir eine Möglichkeit um externe Links zu kennzeichnen.

**Comment by xwolfde** [comment]
Die Nutzung steht in der Readme beschrieben:

Plugin WP External Link
   with Options: 
    - General Settings: Open external link in same window
    - SEO-Settings: Add "external" rel-attribute, please no "nofollow" !
                    Dont use title-Attribut, it messes with accessibility
    - Style Stettings: Icon 19, No icon for external links with images
