### ISSUE TITLE
Auf Akkordeon verlinken

### ISSUE THREAD

**Issue by Alexander-Kotz** [RRZE-Webteam/FAU-Medfak#29]
Hallo zusammen,

ich fände es sehr sinnvoll, wenn man ein Akkordeon verlinken könnte, so dass der Browser an die richtige Stelle springt und dieses gleich geöffnet ist.
Ähnlich wie wenn man einen Anker setzt auf der HP. Ich hoffe das ist machbar..

Viele Grüße
Alexander Kotz

**Comment by xwolfde** [comment]
Im nächsten Update drin.
