### ISSUE TITLE
wpSEO

### ISSUE THREAD

**Issue by AstridSemm** [RRZE-Webteam/FAU-Medfak#3]
Per default wird bei den Bildlinks ja die Möglichkeit angezeigt, Angaben zu wpSEO zu machen; das ist in diesem Fall eher nicht so optimal, von daher wäre es gut, wenn das von vornherein ausgeblendet wäre. Im screenshot habe ich das mal durchgestrichen. 
![bildschirmfoto 2015-08-03 um 09 51 21 kopie](https://cloud.githubusercontent.com/assets/11296947/9033215/7dd6fd90-39c5-11e5-8b13-7b7e7bbd4867.png)

**Comment by xwolfde** [comment]
Als Admin:
 Einstellungen->wpSEO
    Dann Lasche/Accordion "Benutzerdefinierte Felder"

Dort Häckchen wegmachen für dei Felder die wegsollen.
