### ISSUE TITLE
Änderungsbenachrichtigung per E-Mail

### ISSUE THREAD

**Issue by UNiederweis** [RRZE-Webteam/FAU-Medfak#30]
Hallo, Frau Anton und ich bekommen jetzt wechselseitig für jede kleinste Änderung, die wir - sei es auf der deutschen, sei es auf der englischen  Seite vornehmen, per E-Mail eine Fehlermeldung. Das summiert sich am Tag auf locker 20 Mails und mehr. Besteht die Möglichkeit, diese Benachrichtungsfunktion auszuschalten? Wenn ja, wo?
danke.

**Comment by steffigebel** [comment]
geantwortet via Mail!

**Comment by xwolfde** [comment]
Fall schließen nicht vergessen :)
