### ISSUE TITLE
Falscher Screenshot in Theme-Übersichtsseite

### ISSUE THREAD

**Issue by endv02** [RRZE-Webteam/FAU-Medfak#38]
ist wohl mit dem letzten Update verloren gegangen, screenshot.png zeigt das FAU-Einrichtungstheme (übrigens auch bei allen anderen Themes)

**Comment by AstridSemm** [comment]
Guck mal in die Bildergalerien, bitte, da sind sie nämlich alle drin.
Die Screenshots sollen nur einen Überblick über die Menüführung geben, von daher ist die Farbe egal.

**Comment by xwolfde** [comment]
Im nächsten Update repariert
