### ISSUE TITLE
Akkordeons: Überschriften und Farben

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Medfak#4]
Innerhalb von Akkordeons sind die Größenunterschiede der Überschriften in der Rangfolge und im Vergleich zu den Einträgen Collapse "Titel" sehr stark und wurden bemängelt. Zudem haben wir ein Farbproblem. Und die Überschrift en h5 und h6 sind nicht größer als die Normaltextgröße. Natürlich braucht man jetzt keine Überschriften bis h6, das Problem ist aber, dass die eher verwendet werden aufgrund der Größen. Argumentation: Layout. Das darf natürlich keine Argumentation sein, der Kunde weiß das im Zweifel aber nicht und setzt die h's dennoch ein. Siehe Screenshot
![bildschirmfoto 2015-08-07 um 14 18 40](https://cloud.githubusercontent.com/assets/11868989/9135848/e339fb84-3d11-11e5-85de-57eff0385141.png)

**Comment by xwolfde** [comment]
Über die h5 Überschrift kann man reden, die wurde wohl übersehen.
Es steht eh in den Raum die gesamte Accordionhintergrundfläche wieder einheitlich auf Hellgrau zu setzen.

Bei den Rest: Nein, ohne Begründung keine Änderung, da dies von der Grund-CI so kommt, die beschlossen wurde. Das Argument, daß Leute es falsch könnten, können wir nicht akzeptieren, da jeder in der Lage wäre sich schulen zu lassen oder die Doku zu lesen.
Wer dagegen nicht will, der wird auch so Workarounds finden.

**Comment by xwolfde** [comment]
Durch Farbanpassungen erledigt
