### ISSUE TITLE
Bilder

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Medfak#5]
Wie kann man den dateinamen eines Bildes ändern? Wenn man ein Bild ersetzt mit anderem Dateinamen, wird dieser ursprünglich angelegte nicht geändert, selbst wenn man die URL manuell ändert, die ja den alten Namen auch aufnimmt. Das ist seltsam. 
![bildschirmfoto 2015-08-07 um 14 53 52](https://cloud.githubusercontent.com/assets/11868989/9136121/52cade12-3d14-11e5-92a6-8773869d16fa.png)

**Comment by xwolfde** [comment]
Das ist ein Feature, mit dem verhindert werden soll, daß Benutzer aus versehen benutzte Bilder durch neue Bilder ersetzen die zufällig denselben Dateinamen haben. 
Daher kann man einen Dateinamen nicht ändern, zumal bei jedem Upload aus jedem Bild is zu 12 Alternativvarianten für Thumbnails erstellt werden.
