### ISSUE TITLE
Bilder Titel

### ISSUE THREAD

**Issue by steffigebel** [RRZE-Webteam/FAU-Medfak#6]
Wo wird eigentlich der Titel angezeigt. Das Hovern funktioniert hier nicht! Oder geht das bei so Galerien gar nicht?https://www.tst.med.fau.de/2015/08/05/promotionsfeier-2015/
![bildschirmfoto 2015-08-07 um 15 02 47](https://cloud.githubusercontent.com/assets/11868989/9136252/67434ef0-3d15-11e5-891c-e64a7f11cb5f.png)

**Comment by AstridSemm** [comment]
Das Einzige, was im Frontend angezeigt wird, ist die Beschriftung. Der Titel ist für die Mediathek, der Alternativtext für screenreader und bei der Beschreibung muss ich nochmal nachsehen, das weiß ich auswendig jetzt nicht. Weil's mir nicht erinnerlich ist: Was sollte beim Hovern passieren?

**Comment by steffigebel** [comment]
Der Titel ist mit das Wichtisgte für SEO. Der soll beim Hovern angezeigt werden. Ebenso greifen darauf die Parser. Von daher ist es meiner Meinung nach ein Bug. Der zieht ja nicht mal ein Title-Tag. Alt-Tag müsste ja dirn sein, weiss ich jetzt nicht so genau.
--
Stefanie Gebel
Webmanagement
Regionales RechenZentrum Erlangen (RRZE)
Friedrich-Alexander-Universität Erlangen-Nürnberg
Martensstrasse 1, 91058 Erlangen, Germany
Tel. +49 9131 85-27807
stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>
www.rrze.fau.de

Von: Astrid <notifications@github.com<mailto:notifications@github.com>>
Antworten an: RRZE-Webteam/FAU-Medfak <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Freitag, 7. August 2015 15:08
An: RRZE-Webteam/FAU-Medfak <FAU-Medfak@noreply.github.com<mailto:FAU-Medfak@noreply.github.com>>
Cc: "Gebel, Stefanie" <stefanie.gebel@fau.de<mailto:stefanie.gebel@fau.de>>
Betreff: Re: [FAU-Medfak] Bilder Titel (#6)


Das Einzige, was im Frontend angezeigt wird, ist die Beschriftung. Der Titel ist für die Mediathek, der Alternativtext für screenreader und bei der Beschreibung muss ich nochmal nachsehen, das weiß ich auswendig jetzt nicht. Weil's mir nicht erinnerlich ist: Was sollte beim Hovern passieren?

**Comment by xwolfde** [comment]
Das mit dem Hovern hat doch überhaupt nichts mit SEO zu tun. 
Das ist nur eine Sache, die einige machen um den Titel anzuzeigen. Allerdings darf man das garnicht tun, wenn der Titel bereits unter dem Bild erscheint. Denn wenn man das tun würde, würde für Screenreader der Titel doppelt vorgelesen werden, was dann tatsächlich ein Bug ist.

**Comment by steffigebel** [comment]
Also das habe ich anders beigebracht bekommen. Hier mal eine Auszug zur Verdeutlichung: 

" dasTitle-Attribut erscheint im Browser als „Tooltip“. Wenn man mit dem Cursor auf ein Element mit Title-Attribut rollt, so erscheint nach kurzer Zeit eine Art „Layer mit Erklärungstext“. Und zwar ist genau der Text zu lesen, der im Title-Attribut gesetzt wird. Das Title-Attribut ist also eine zusätzliche Information, und keine alternative. Der legendäre Internet-Explorer 6 hatte die „Macke“, dass er statt des Title-Textes den Alt-Text als Tooltip angezeigt hat. Auch daher stammt das Gerücht, dass der Alt-Text der „Tooltip“-Text sei.

Viele Webdesigner/Programmierer orientieren sich beim Erstellen des HTML-Codes an den Vorgaben des W3C, die wunderbar auf der „SelfHTML„-Seite beschrieben sind. Auf der Seite der Tag-Attribute wird beim Image-Tag allerdings nicht das Title-Attribut aufgelistet. Daher sind viele der Meinung, dass man das „Title-Attribut bei Bildern“ überhaupt nicht setzen darf. Das ist allerdings nicht richtig. Denn „Title“ ist ein sog. Universal-Attribut, dass in fast allen vielen Tags gesetzt werden darf.
Das Title-Attribut kann als Tooltip für den Benutzer durchaus hilfreich sein – insbesondere dann, wenn ein Bild keine sichtbare Bildunterschrift hat. Ich würde daher empfehlen, es zu setzen. Zumindest eben dann, wenn die Bilder – aus welchen Gründen auch immer – keine Bildunterschrift haben."

**Comment by xwolfde** [comment]
Ab WP4.4 haben wir als neuen Bildcaption Tag das <figcaption> . Dies wird von den Suchmaschinen entsprechend unterstützt
