### ISSUE TITLE
Bildbeschreibung in Bühnenbild als Overlay 

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Medfak#9]
Bildbeschriebung soll angezeigt werden bei Bühnenbildern.

**Comment by AstridSemm** [comment]
Eigentlich sollte es die Möglichkeit geben, bei allen Bildern (abgesehen von den Thumbnails) eine Urheberrechtsangabe plus Namensnennung zu machen. Ob man sich dafür auf die Bildbeschreibung festlegen sollte, wäre zu überdenken. Wofür wird sie denn noch genutzt?

**Comment by xwolfde** [comment]
Done.
Reihenfolge der Wahl, je nachdem ob das Feld belegt ist.
1. copyright-info des Bildes (Meta Angabe IPTX)
2. Bildbeschreibung
3. Bildunterschrift
4. Alt
